# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/submitit/%j
timeout_min: 600
cpus_per_task: 1
gpus_per_node: null
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: normal
comment: null
constraint: null
exclude: null
gres: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: ${n_envs}G
account: ec29
array_parallelism: null
signal_delay_s: 120